/IronFilter/det/setFilterCellSpacing 86.0 cm #76.0 cm
/IronFilter/det/setPolyHeight 28.0 cm #scandium length or the bore length
/IronFilter/det/setMultiplierLeadHeightFront 25.0 cm
/IronFilter/det/setModeratorAluminumHeight 40 cm
/IronFilter/det/setModeratorTitaniumHeight 7.0 cm # to get the DT position add the number till here
/IronFilter/det/setMultiplierLeadHeightRear 24.0 cm
/IronFilter/det/setMultiplierLeadRadius 22.86 cm
/IronFilter/det/setModeratorAluminumRadius 22.86 cm
/IronFilter/det/setModeratorTitaniumRadius 22.86 cm
/IronFilter/det/setTestX 0 m
/IronFilter/det/setTestY 0 m
/IronFilter/det/setTestZ 0 m


/run/initialize
/tracking/verbose 1

/random/setSeeds 1233 4388

/process/list


/gps/particle geantino
#/gps/position 0 0 100.0 cm
#/gps/position 35 0 -50 cm
#/gps/position 0 0 0 cm
#/gps/direction 0 1 0
/gps/position 10 186 0 cm
/gps/direction 0 -1 0


/analysis/setFileName testgeantino
/run/beamOn 1
